//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alwi_Laptop_Mart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Cart()
        {
            this.tbl_OrderHistory = new HashSet<tbl_OrderHistory>();
        }
    
        public int CartId { get; set; }
        public byte[] ProductIcon { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AdminId { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_Admin tbl_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderHistory> tbl_OrderHistory { get; set; }
    }
}
