//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alwi_Laptop_Mart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_Cart = new HashSet<tbl_Cart>();
            this.tbl_OrderHistory = new HashSet<tbl_OrderHistory>();
        }
    
        public int ProductID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public byte[] Image { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string Display { get; set; }
        public string Storage { get; set; }
        public string Processor { get; set; }
        public string RAM { get; set; }
        public string Warranty { get; set; }
        public string GraphicCard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cart> tbl_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderHistory> tbl_OrderHistory { get; set; }
    }
}
