//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alwi_Laptop_Mart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderHistory
    {
        public int OrderId { get; set; }
        public string UserName { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string Email { get; set; }
    
        public virtual tbl_Admin tbl_Admin { get; set; }
        public virtual tbl_Cart tbl_Cart { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
